### ISSUE TITLE
`Record AppMaps` appears as completed in the sidebar despite no AppMaps created

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/vscode-appland#550]
> on a machine that has never run AppMap before

> This is definitely a brand new clone of rails sample app on a machine that hasn't run it before

![Image](https://user-images.githubusercontent.com/8737782/206008257-a7db9aba-00b0-41a4-8785-bfc656134104.png)

**Comment by kgilpin** [comment]
Related: the “Waiting for AppMaps to be created” looks a bit more like a Status than what we have in some other places. Primarily due to the wait animation / icon. But it’s still not as obviously Statusy as it could be. And also, it’s not clear what “Waiting for AppMaps to be created” means and what the user can do about it. Consider changing it to a simple label like “No AppMaps in this project” and then having a details section under the status, or a link, that the user can consult for more information.
